name: This should build
on: [ push, pull_request ]

jobs:
  build-gcc-64:
    runs-on: ubuntu-latest
    steps:
    - name: Install GCC
      run: sudo apt install gcc-multilib
    - uses: actions/checkout@v4
    - name: Compile
      run: make clean all

  build-gcc-32:
    runs-on: ubuntu-latest
    steps:
    - name: Install GCC
      run: sudo apt install gcc-multilib
    - uses: actions/checkout@v4
    - name: Compile
      run: CC="gcc -m32" make clean all

  build-clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-linux-gnu, x86_64, riscv32, riscv64, arm, arm64 ]
    steps:
    - name: Download clang
      run: sudo apt install clang gcc-multilib lld
    - uses: actions/checkout@v4
    - name: Compile
      run: CC="clang --target=${{ matrix.target }} -fuse-ld=lld" make clean all
